name: CI-CD
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch: 
env: 
  AZURE_WEBAPP_NAME: conversao-live
  NODE_VERSION: '18.x'
jobs: 
  CI:
    runs-on: ubuntu-latest
    steps: 
    - name: Obtendo o código do repositório
      uses: actions/checkout@v3.5.2
    - name: Setup ambiente Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./src/package-lock.json
    
    - name: Execução do npm install e o teste
      run: |
        npm install
        npm run test
      working-directory: ./src
      
