name: CI-CD
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch: 
env: 
  AZURE_WEBAPP_NAME: conversao-live
  NODE_VERSION: '18.x'
jobs: 
  CI:
    runs-on: ubuntu-latest
    steps: 
    - name: Obtendo o código do repositório
      uses: actions/checkout@v3.5.2
    - name: Setup ambiente Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./src/package-lock.json
    
    - name: Execução do npm install e o teste
      run: |
        npm install
        npm run test
      working-directory: ./src
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      
    - name: Construção da imagem de container da aplicação
      uses: docker/build-push-action@v4.0.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          fabricioveronez/conversao-live:latest
          fabricioveronez/conversao-live:v${{ github.run_number }}
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps: 
    - name: Deploy no Azure Web App
      uses: Azure/webapps-deploy@v2.2.5
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: fabricioveronez/conversao-live:v${{ github.run_number }}
          
        
    
      
